[package]
name = "corroded_boy"
version = "0.1.0"
authors = ["Simon Hostettler <simon.hostettler@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
